<div class="signup-form">
                        <h2>Авторизация на сайте</h2>
                        <form action="" method="post">                            
                            <input type="login" name="login" placeholder="LOGIN" />
                            <input type="password" name="password" placeholder="PASSWORD"/>
                            <input type="submit" name="submit" value="Войти" />
                            <input type="submit" name="logout" value="Выйти" />
                        </form>
</div>